name: medi_scan_flutter
description: Instantly verify your medicines.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_database: ^11.0.1

  # Barcode Scanner
  flutter_barcode_scanner: ^2.0.0

  # For date formatting
  intl: ^0.19.0

  # For launching emails
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # If you add a logo image to an 'assets' folder, uncomment these lines
  # assets:
  #   - assets/app_logo.jpg

