name: medi_scan_flutter
description: Instantly verify your medicines.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_database: ^11.0.1

  # Barcode Scanning
  mobile_scanner: ^7.1.2       # ✅ Works for iOS, Android, and Web (real-time camera)
  # flutter_barcode_sdk: 2.2.0  # ❌ Removed to avoid conflict — not needed anymore

  # Permissions (for mobile platforms)
  permission_handler: ^11.1.0

  # Utilities
  intl: ^0.19.0                 # Date/time formatting
  url_launcher: ^6.3.0          # For launching links or emails

  # UI & Icons
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_nobg.png
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
