// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCasFD8lfFtLbNGOUoQZ-7awCm6gFch1Rg',
    appId: '1:249198522863:android:5e6f408a5091547f1e061a',
    messagingSenderId: '249198522863',
    projectId: 'mediscan-30e5a',
    databaseURL: 'https://mediscan-30e5a-default-rtdb.firebaseio.com',
    storageBucket: 'mediscan-30e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh9nNIoqmwx12stwLumOdLOHT9Q9FO4GQ',
    appId: '1:249198522863:ios:767b23996efbebd91e061a',
    messagingSenderId: '249198522863',
    projectId: 'mediscan-30e5a',
    databaseURL: 'https://mediscan-30e5a-default-rtdb.firebaseio.com',
    storageBucket: 'mediscan-30e5a.firebasestorage.app',
    iosBundleId: 'com.example.mediScanFlutter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUG27mnQ3nm10R5I91-UA5eUx5lQLUseg',
    appId: '1:249198522863:web:1154b94f3dd187bb1e061a',
    messagingSenderId: '249198522863',
    projectId: 'mediscan-30e5a',
    authDomain: 'mediscan-30e5a.firebaseapp.com',
    databaseURL: 'https://mediscan-30e5a-default-rtdb.firebaseio.com',
    storageBucket: 'mediscan-30e5a.firebasestorage.app',
    measurementId: 'G-GPT0YR43RQ',
  );

}