import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:medi_scan_flutter/firebase_options.dart'; // Import the generated file
import 'package:medi_scan_flutter/screens/add_medicine_screen.dart';
import 'package:medi_scan_flutter/screens/history_screen.dart';
import 'package:medi_scan_flutter/screens/home_screen.dart';
import 'package:medi_scan_flutter/screens/result_screen.dart';
import 'package:medi_scan_flutter/models/drug_data.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Use the DefaultFirebaseOptions generated by the 'flutterfire configure' command
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MediScanApp());
}

class MediScanApp extends StatelessWidget {
  const MediScanApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MediScan',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: const Color(0xFFF8F9FA),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 1,
          iconTheme: IconThemeData(color: Color(0xFF2D3436)),
          titleTextStyle: TextStyle(
            color: Color(0xFF2D3436),
            fontSize: 20,
            fontWeight: FontWeight.w600,
          ),
        ),
      ),
      debugShowCheckedModeBanner: false,
      initialRoute: '/home',
      routes: {
        '/home': (context) => const HomeScreen(),
        '/add_medicine': (context) => const AddMedicineScreen(),
        '/history': (context) => const HistoryScreen(),
        '/result': (context) {
          final args = ModalRoute.of(context)!.settings.arguments as Map<String, dynamic>;
          return ResultScreen(
            scannedCode: args['scannedCode'],
            drug: args['drug'] as DrugData?,
          );
        },
      },
    );
  }
}

